### ISSUE TITLE
NS2 and NS2T SHOULD be DNSSEC signed

### ISSUE THREAD

**Issue by timapril** [timapril/ns2#2]
When ever authoritative (both in parent and child zones), NS2 and NS2T records should be signed.

**Comment by jdreed** [comment]
(copying from discussion elsewhere)

I think it's worth touching on recommendations if only one can be signed?  (Which I think it usually the parent, since all the major TLDs are signed).

**Comment by jrlevine** [comment]
In a zone file, only the NS at the apex are signed. The other NS at zone cuts are glue and are not signed.
Adding to the confusion, the DS records at the zone cut _are_ signed, and have to match the signed DNSKEY at the child zone apex.
I think it would be a problem to have competing authoritative RRSETs for the same rrtype and same name in parent and child. It would be a large change to DNSSEC semantics where currently there is only one source for any signed RRSET. (Multiple servers with the same zone as considered to be the same source.)
