### ISSUE TITLE
NS2 and NS2T SHOULD appear in parent and child

### ISSUE THREAD

**Issue by timapril** [timapril/ns2#3]
In the event that the parent does not support NS2, the records may be omitted. Resolvers that wish to use encrypted transport to authority servers MAY send a NS2 query to the child using the delegated nameservers from the parent.

**Comment by jrlevine** [comment]
The NS records at the top of the child zone are authoritative. The ones in the parent are just glue. You need NS in the parent because that's the signal for a zone cut and I wouldn't change that, even though the client may ignore them in favor of NS2 or NS2T.
