### ISSUE TITLE
ipv4hint and ipv6hint

### ISSUE THREAD

**Issue by jrlevine** [timapril/ns2#5]
Recent discussions in DNSOP make it clear that it's mandatory to return A and AAAA glue so these hints are redundant in NS2.

**Comment by timapril** [comment]
Good point. I'll pull that section and  I will add a section that indicates that in-baliwick glue for a delegation is required, like with NS records.

**Comment by timapril** [comment]
I forgot to include something about the in-bailiwick glue requirement

**Comment by timapril** [comment]
Never mind it was already covered in the section "When to include glue"
